name: flourish
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  rive: ^0.13.20
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  envied: ^1.1.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  http_parser: ^4.1.2
  path: ^1.9.0
  audioplayers: ^6.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  mockito: ^5.4.2

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - default_plants/images/leucojum_vernum.jpg
    - default_plants/plantInfo/leucojum_vernum.json
    - default_plants/images/hibiscus_rosa_sinensis.jpg
    - default_plants/plantInfo/hibiscus_rosa_sinensis.json
    - badges/plant_1.riv
    - badges/plant_2.riv
    - badges/plant_3.riv
    - badges/plant_4.riv
    - badges/plant_5.riv
    - badges/plant_6.riv
    - badges/plant_7.riv
    - badges/plant_8.riv
    - badges/plant_9.riv
    - assets/sounds/chill_alert.mp3
    - assets/sounds/badge_unlock.mp3
    - test/assets/images/test_plant.jpg
    - test/assets/images/dog.jpg
    - test/assets/responses/sample_plant_info_response.json
